import type { AutomationTargetRow } from '../types'

// ── Mock automation targets data ──────────────────────────────────────────────
// Rows are flat and sorted by Domain → L1 → L2 → L3 → L4 so that the
// de-duplication logic in column definitions correctly hides repeated labels.
//
// Structure:
//   1 Domain
//   2 Level 1s (EXP, DWE)
//   3 Level 2s: EXP.1 (1st, 1 L3), DWE.1 (2nd, 3 L3s), DWE.2 (3rd/last, 1 L3)
//   5 Level 3s: L3-1 → 4 L4s; L3-2 leaf; L3-3 leaf; L3-4 → 2 L4s; L3-5 leaf
//
// Rows where level4 / level4Code are '' are LEAF L3 rows — the L3 itself is
// the process. generateDisplayRows will NOT wrap them in a synthetic header.

export const AUTOMATION_TARGETS_DATA: AutomationTargetRow[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // L1: Exploration (EXP)  ▸  L2: Field Development Planning (EXP.1)
  // L3-1: Subsurface Evaluation (EXP.1.1)  →  4 Level 4s
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'at-001',
    domain: 'Oil & Gas Operations',
    level1: 'Exploration',
    level1Code: 'EXP',
    level2: 'Field Development Planning',
    level2Code: 'EXP.1',
    level3: 'Subsurface Evaluation',
    level3Code: 'EXP.1.1',
    level4: 'Seismic Data Interpretation',
    level4Code: 'EXP.1.1.1',
    groupCompany: 'ADNOC Offshore',
    site: 'Das Island',
    status: 'Published',
    processDescription:
      'Interpreting 3D seismic volumes to identify structural traps and stratigraphic features.',
    smeFeedback: '',
    processCriticality: 'Critical',
    numberOfPeopleInvolved: 'Medium (100-500)',
    scaleOfProcess: 'Medium: (bigger team within one department)',
    automationMaturityLevel: 'Semi-Automated',
    automationLevel: '40%',
    currentApplicationsSystems: ['Petrel', 'Kingdom'],
    ongoingAutomation: 'Automated horizon picking pilot',
    businessRecommendation: 'Full automation with AI-assisted picking',
    keyChallenges: 'Complex fault systems require expert review',
    aiPowered: 'Yes',
    aiPoweredUseCase: 'ML-based fault detection',
    autonomousUseCaseEnabled: 'No',
    autonomousUseCaseDescription: '',
    processCycle: 'Quarterly',
    processRepetitionWithinCycle: '3',
    totalPersonnelFTE: '4',
    totalProcessDurationDays: '15',
    timeSpentManualPercent: '55%',
    dailyRateCardAED: '2,800',
    keyManualSteps: 'Horizon picking, Fault interpretation, Depth conversion',
    annualCostOfManualEffortAED: '9,240,000.00000',
    northStarTarget: 'Fully Automated',
    targetAutomationLevelPercent: '90%',
    toBeAIPowered: 'Yes',
    toBeAIPoweredComments: 'AI-assisted seismic attribute analysis',
    rateCardAED: '150,000',
    costOfManualEffortAED: '420,000',
    publishedDate: '12 Dec 2025',
    submittedBy: 'Khawla Al Ketbi',
    submittedDate: '9 Nov 2025',
  },
  {
    id: 'at-002',
    domain: 'Oil & Gas Operations',
    level1: 'Exploration',
    level1Code: 'EXP',
    level2: 'Field Development Planning',
    level2Code: 'EXP.1',
    level3: 'Subsurface Evaluation',
    level3Code: 'EXP.1.1',
    level4: 'Well Log Analysis',
    level4Code: 'EXP.1.1.2',
    groupCompany: 'ADNOC Offshore',
    site: 'Das Island',
    status: 'Pending signoff',
    processDescription:
      'Analysing petrophysical well logs to define reservoir zones and fluid contacts.',
    smeFeedback: '',
    processCriticality: 'Standard',
    numberOfPeopleInvolved: 'Low (1-100)',
    scaleOfProcess: 'Small: (single team)',
    automationMaturityLevel: 'Partially Automated',
    automationLevel: '50%',
    currentApplicationsSystems: ['Techlog', 'IP'],
    ongoingAutomation: 'Automated log QC routines',
    businessRecommendation: 'Automate zone picking with supervised ML',
    keyChallenges: 'Variable log quality across vintage wells',
    aiPowered: 'No',
    aiPoweredUseCase: '',
    autonomousUseCaseEnabled: 'No',
    autonomousUseCaseDescription: '',
    processCycle: 'Per Well',
    processRepetitionWithinCycle: '1',
    totalPersonnelFTE: '2',
    totalProcessDurationDays: '5',
    timeSpentManualPercent: '45%',
    dailyRateCardAED: '2,200',
    keyManualSteps: 'Log quality check, Zone definition, Fluid contact picking',
    annualCostOfManualEffortAED: '3,960,000.00000',
    northStarTarget: 'Fully Automated',
    targetAutomationLevelPercent: '80%',
    toBeAIPowered: 'Yes',
    toBeAIPoweredComments: 'Supervised classification of lithofacies from logs',
    rateCardAED: '110,000',
    costOfManualEffortAED: '290,000',
    publishedDate: '12 Dec 2025',
    submittedBy: 'Khawla Al Ketbi',
    submittedDate: '9 Nov 2025',
  },
  {
    id: 'at-003',
    domain: 'Oil & Gas Operations',
    level1: 'Exploration',
    level1Code: 'EXP',
    level2: 'Field Development Planning',
    level2Code: 'EXP.1',
    level3: 'Subsurface Evaluation',
    level3Code: 'EXP.1.1',
    level4: 'Reservoir Characterisation',
    level4Code: 'EXP.1.1.3',
    groupCompany: 'ADNOC Onshore',
    site: 'Habshan',
    status: 'Pending updates',
    processDescription: 'Building static reservoir models integrating seismic and well data.',
    smeFeedback: '<p>Needs updated core data from recent wells</p>',
    processCriticality: 'Critical',
    numberOfPeopleInvolved: 'Medium (100-500)',
    scaleOfProcess: 'Large: (cross-department)',
    automationMaturityLevel: 'Manual',
    automationLevel: '20%',
    currentApplicationsSystems: ['Petrel', 'RMS'],
    ongoingAutomation: 'None',
    businessRecommendation: 'Cloud-based collaborative modelling platform',
    keyChallenges: 'Data heterogeneity across formations',
    aiPowered: 'No',
    aiPoweredUseCase: '',
    autonomousUseCaseEnabled: 'No',
    autonomousUseCaseDescription: '',
    processCycle: 'Annual',
    processRepetitionWithinCycle: '1',
    totalPersonnelFTE: '6',
    totalProcessDurationDays: '45',
    timeSpentManualPercent: '70%',
    dailyRateCardAED: '3,000',
    keyManualSteps: 'Facies modelling, Porosity population, Model upscaling',
    annualCostOfManualEffortAED: '12,600,000.00000',
    northStarTarget: 'Partially Automated',
    targetAutomationLevelPercent: '60%',
    toBeAIPowered: 'Yes',
    toBeAIPoweredComments: 'Generative AI for facies model ensemble',
    rateCardAED: '200,000',
    costOfManualEffortAED: '600,000',
    publishedDate: '',
    submittedBy: 'Khawla Al Ketbi',
    submittedDate: '20 Dec 2025',
  },
  {
    id: 'at-004',
    domain: 'Oil & Gas Operations',
    level1: 'Exploration',
    level1Code: 'EXP',
    level2: 'Field Development Planning',
    level2Code: 'EXP.1',
    level3: 'Subsurface Evaluation',
    level3Code: 'EXP.1.1',
    level4: 'Volumetric Estimation',
    level4Code: 'EXP.1.1.4',
    groupCompany: 'ADNOC Onshore',
    site: 'Habshan',
    status: 'Draft',
    processDescription: 'Calculating original oil and gas in place from static reservoir models.',
    smeFeedback: '',
    processCriticality: 'Standard',
    numberOfPeopleInvolved: 'Low (1-100)',
    scaleOfProcess: 'Small: (single team)',
    automationMaturityLevel: 'Semi-Automated',
    automationLevel: '55%',
    currentApplicationsSystems: ['Petrel', 'OpenWorks'],
    ongoingAutomation: 'Scripted Monte Carlo runs',
    businessRecommendation: 'Full probabilistic automation with audit trail',
    keyChallenges: 'Uncertainty quantification requires expert sign-off',
    aiPowered: 'No',
    aiPoweredUseCase: '',
    autonomousUseCaseEnabled: 'No',
    autonomousUseCaseDescription: '',
    processCycle: 'Annual',
    processRepetitionWithinCycle: '1',
    totalPersonnelFTE: '2',
    totalProcessDurationDays: '7',
    timeSpentManualPercent: '35%',
    dailyRateCardAED: '2,400',
    keyManualSteps: 'Cut-off selection, Net-to-gross calculation, Uncertainty scenarios',
    annualCostOfManualEffortAED: '2,184,000.00000',
    northStarTarget: 'Fully Automated',
    targetAutomationLevelPercent: '85%',
    toBeAIPowered: 'No',
    toBeAIPoweredComments: '',
    rateCardAED: '100,000',
    costOfManualEffortAED: '250,000',
    publishedDate: '12 Dec 2025',
    submittedBy: 'Khawla Al Ketbi',
    submittedDate: '9 Nov 2025',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // L1: Drilling & Well Engineering (DWE)  ▸  L2: Well Planning (DWE.1)
  // L3-2: Well Trajectory Design (DWE.1.1)  →  LEAF (no Level 4)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'at-005',
    domain: 'Oil & Gas Operations',
    level1: 'Drilling & Well Engineering',
    level1Code: 'DWE',
    level2: 'Well Planning',
    level2Code: 'DWE.1',
    level3: 'Well Trajectory Design',
    level3Code: 'DWE.1.1',
    level4: '',
    level4Code: '',
    groupCompany: 'ADNOC Drilling',
    site: 'General',
    status: 'Published',
    processDescription:
      'Designing optimal 3D well trajectories to reach subsurface targets safely and efficiently.',
    smeFeedback: '',
    processCriticality: 'Standard',
    numberOfPeopleInvolved: 'Low (1-100)',
    scaleOfProcess: 'Small: (single team)',
    automationMaturityLevel: 'Partially Automated',
    automationLevel: '45%',
    currentApplicationsSystems: ['WellPlan', 'Landmark'],
    ongoingAutomation: 'Automated anti-collision checks',
    businessRecommendation: 'Full trajectory optimisation automation',
    keyChallenges: 'Real-time rig sensor integration',
    aiPowered: 'No',
    aiPoweredUseCase: '',
    autonomousUseCaseEnabled: 'No',
    autonomousUseCaseDescription: '',
    processCycle: 'Per Well',
    processRepetitionWithinCycle: '1',
    totalPersonnelFTE: '1.5',
    totalProcessDurationDays: '3',
    timeSpentManualPercent: '50%',
    dailyRateCardAED: '1,800',
    keyManualSteps: 'Target definition, Survey programme, Anti-collision review',
    annualCostOfManualEffortAED: '1,485,000.00000',
    northStarTarget: 'Fully Automated',
    targetAutomationLevelPercent: '80%',
    toBeAIPowered: 'No',
    toBeAIPoweredComments: '',
    rateCardAED: '90,000',
    costOfManualEffortAED: '240,000',
    publishedDate: '12 Dec 2025',
    submittedBy: 'Khawla Al Ketbi',
    submittedDate: '9 Nov 2025',
  },

  // ─── L3-3: Mud Programme (DWE.1.2)  →  LEAF ──────────────────────────────

  {
    id: 'at-006',
    domain: 'Oil & Gas Operations',
    level1: 'Drilling & Well Engineering',
    level1Code: 'DWE',
    level2: 'Well Planning',
    level2Code: 'DWE.1',
    level3: 'Mud Programme',
    level3Code: 'DWE.1.2',
    level4: '',
    level4Code: '',
    groupCompany: 'ADNOC Drilling',
    site: 'General',
    status: 'Pending updates',
    processDescription:
      'Specifying drilling fluid types, densities, and volumes for each well section.',
    smeFeedback: '<p>Fluid selection needs alignment with new HSE guidelines</p>',
    processCriticality: 'Critical',
    numberOfPeopleInvolved: 'Low (1-100)',
    scaleOfProcess: 'Small: (single team)',
    automationMaturityLevel: 'Manual',
    automationLevel: '15%',
    currentApplicationsSystems: ['Landmark', 'MI SWACO DrillBench'],
    ongoingAutomation: 'None',
    businessRecommendation: 'Automate hydraulics modelling and fluid selection logic',
    keyChallenges: 'Dependencies on pore pressure uncertainty',
    aiPowered: 'No',
    aiPoweredUseCase: '',
    autonomousUseCaseEnabled: 'No',
    autonomousUseCaseDescription: '',
    processCycle: 'Per Well',
    processRepetitionWithinCycle: '1',
    totalPersonnelFTE: '2',
    totalProcessDurationDays: '4',
    timeSpentManualPercent: '75%',
    dailyRateCardAED: '2,000',
    keyManualSteps: 'Hydraulics calculation, Fluid volume estimation, Contingency planning',
    annualCostOfManualEffortAED: '2,400,000.00000',
    northStarTarget: 'Partially Automated',
    targetAutomationLevelPercent: '60%',
    toBeAIPowered: 'No',
    toBeAIPoweredComments: '',
    rateCardAED: '95,000',
    costOfManualEffortAED: '260,000',
    publishedDate: '',
    submittedBy: 'Khawla Al Ketbi',
    submittedDate: '20 Dec 2025',
  },

  // ─── L3-4: Casing Design (DWE.1.3)  →  2 Level 4s ───────────────────────

  {
    id: 'at-007',
    domain: 'Oil & Gas Operations',
    level1: 'Drilling & Well Engineering',
    level1Code: 'DWE',
    level2: 'Well Planning',
    level2Code: 'DWE.1',
    level3: 'Casing Design',
    level3Code: 'DWE.1.3',
    level4: 'Casing String Selection',
    level4Code: 'DWE.1.3.1',
    groupCompany: 'ADNOC Drilling',
    site: 'General',
    status: 'Draft',
    processDescription: 'Selecting appropriate casing grades and weights for each hole section.',
    smeFeedback: '',
    processCriticality: 'Standard',
    numberOfPeopleInvolved: 'Low (1-100)',
    scaleOfProcess: 'Small: (single team)',
    automationMaturityLevel: 'Semi-Automated',
    automationLevel: '50%',
    currentApplicationsSystems: ['WellPlan', 'StressCheck'],
    ongoingAutomation: 'Automated torque & drag calculations',
    businessRecommendation: 'Automated casing selection using well database analytics',
    keyChallenges: 'Supplier catalogue variations',
    aiPowered: 'No',
    aiPoweredUseCase: '',
    autonomousUseCaseEnabled: 'No',
    autonomousUseCaseDescription: '',
    processCycle: 'Per Well',
    processRepetitionWithinCycle: '1',
    totalPersonnelFTE: '1.5',
    totalProcessDurationDays: '2',
    timeSpentManualPercent: '40%',
    dailyRateCardAED: '1,800',
    keyManualSteps: 'Load analysis, Grade selection, Collapse check',
    annualCostOfManualEffortAED: '1,080,000.00000',
    northStarTarget: 'Fully Automated',
    targetAutomationLevelPercent: '85%',
    toBeAIPowered: 'Yes',
    toBeAIPoweredComments: 'AI-driven casing selection from historical offsets',
    rateCardAED: '80,000',
    costOfManualEffortAED: '200,000',
    publishedDate: '12 Dec 2025',
    submittedBy: 'Khawla Al Ketbi',
    submittedDate: '9 Nov 2025',
  },
  {
    id: 'at-008',
    domain: 'Oil & Gas Operations',
    level1: 'Drilling & Well Engineering',
    level1Code: 'DWE',
    level2: 'Well Planning',
    level2Code: 'DWE.1',
    level3: 'Casing Design',
    level3Code: 'DWE.1.3',
    level4: 'Casing Load Analysis',
    level4Code: 'DWE.1.3.2',
    groupCompany: 'ADNOC Drilling',
    site: 'General',
    status: 'Pending signoff',
    processDescription: 'Computing burst, collapse, and tension loads across all casing strings.',
    smeFeedback: '',
    processCriticality: 'Critical',
    numberOfPeopleInvolved: 'Low (1-100)',
    scaleOfProcess: 'Small: (single team)',
    automationMaturityLevel: 'Partially Automated',
    automationLevel: '55%',
    currentApplicationsSystems: ['StressCheck'],
    ongoingAutomation: 'Scripted load case generation',
    businessRecommendation: 'Fully automate load profiles with real-time pore pressure feeds',
    keyChallenges: 'Uncertain formation pressure data',
    aiPowered: 'No',
    aiPoweredUseCase: '',
    autonomousUseCaseEnabled: 'No',
    autonomousUseCaseDescription: '',
    processCycle: 'Per Well',
    processRepetitionWithinCycle: '1',
    totalPersonnelFTE: '1',
    totalProcessDurationDays: '2',
    timeSpentManualPercent: '40%',
    dailyRateCardAED: '1,800',
    keyManualSteps: 'Load combination setup, Safety factor verification, Report',
    annualCostOfManualEffortAED: '720,000.00000',
    northStarTarget: 'Fully Automated',
    targetAutomationLevelPercent: '90%',
    toBeAIPowered: 'No',
    toBeAIPoweredComments: '',
    rateCardAED: '75,000',
    costOfManualEffortAED: '180,000',
    publishedDate: '12 Dec 2025',
    submittedBy: 'Khawla Al Ketbi',
    submittedDate: '9 Nov 2025',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // L1: Drilling & Well Engineering (DWE)  ▸  L2: Well Completion (DWE.2)
  // L3-5: Completion Design Review (DWE.2.1)  →  LEAF (no Level 4)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'at-009',
    domain: 'Oil & Gas Operations',
    level1: 'Drilling & Well Engineering',
    level1Code: 'DWE',
    level2: 'Well Completion',
    level2Code: 'DWE.2',
    level3: 'Completion Design Review',
    level3Code: 'DWE.2.1',
    level4: '',
    level4Code: '',
    groupCompany: 'ADNOC Drilling',
    site: 'General',
    status: 'Published',
    processDescription:
      'Reviewing and approving completion string configurations and perforation strategies.',
    smeFeedback: '',
    processCriticality: 'Standard',
    numberOfPeopleInvolved: 'Low (1-100)',
    scaleOfProcess: 'Small: (single team)',
    automationMaturityLevel: 'Manual',
    automationLevel: '20%',
    currentApplicationsSystems: ['CPLAN', 'Landmark'],
    ongoingAutomation: 'None',
    businessRecommendation: 'Standardise review templates and automate checklist validation',
    keyChallenges: 'Multi-disciplinary sign-off required',
    aiPowered: 'No',
    aiPoweredUseCase: '',
    autonomousUseCaseEnabled: 'No',
    autonomousUseCaseDescription: '',
    processCycle: 'Per Well',
    processRepetitionWithinCycle: '1',
    totalPersonnelFTE: '3',
    totalProcessDurationDays: '5',
    timeSpentManualPercent: '65%',
    dailyRateCardAED: '2,200',
    keyManualSteps:
      'Completion string check, Perforation interval review, Fluid compatibility check',
    annualCostOfManualEffortAED: '2,145,000.00000',
    northStarTarget: 'Partially Automated',
    targetAutomationLevelPercent: '50%',
    toBeAIPowered: 'No',
    toBeAIPoweredComments: '',
    rateCardAED: '85,000',
    costOfManualEffortAED: '215,000',
    publishedDate: '12 Dec 2025',
    submittedBy: 'Khawla Al Ketbi',
    submittedDate: '9 Nov 2025',
  },
]
