import type { AutomationTargetRow } from '../types'

// ── Mock automation targets data ──────────────────────────────────────────────
// Rows are flat and sorted by Domain → L1 → L2 → L3 → L4 so that the
// de-duplication logic in the column definitions correctly hides repeated
// Domain / L1 / L2 / L3 labels in subsequent rows of the same group.

export const AUTOMATION_TARGETS_DATA: AutomationTargetRow[] = [
  // ── Exploration & Planning  ▸ EXP.2.1 — Field Development Plan Preparation ──
  {
    id: 'at-001',
    domain: 'Exploration & Planning',
    level1: 'Exploration',
    level1Code: 'EXP',
    level2: 'Field Development Planning',
    level2Code: 'EXP.2',
    level3: 'Field Development Plan Preparation',
    level3Code: 'EXP.2.1',
    level4: 'Subsurface Data Integration',
    level4Code: 'EXP.2.1.1',
    groupCompany: 'ADNOC Offshore',
    site: 'Das Island',
    status: 'Published',
    processDescription: 'Integrating subsurface data across multiple geological surveys',
    smeFeedback: '',
    processCriticality: 'Standard',
    numberOfPeopleInvolved: 'High (500-1000)',
    scaleOfProcess: 'Medium: (bigger team within one department)',
    automationMaturityLevel: 'Partially Automated',
    automationLevel: '35%',
    currentApplicationsSystems: ['SAP', 'Petrel'],
    ongoingAutomation: 'RPA for data extraction',
    businessRecommendation: 'Full automation recommended',
    keyChallenges: 'Legacy systems integration',
    aiPowered: 'No',
    aiPoweredUseCase: '',
    autonomousUseCaseEnabled: 'No',
    autonomousUseCaseDescription: '',
    processCycle: 'Monthly',
    processRepetitionWithinCycle: '4',
    totalPersonnelFTE: '3.5',
    totalProcessDurationDays: '12',
    timeSpentManualPercent: '60%',
    dailyRateCardAED: '2,500',
    keyManualSteps: 'Data collection, Validation, Report generation',
    annualCostOfManualEffortAED: '11,696,400.00000',
    northStarTarget: 'Fully Automated',
    targetAutomationLevelPercent: '90%',
    toBeAIPowered: 'Yes',
    toBeAIPoweredComments: 'AI for anomaly detection in subsurface data',
    rateCardAED: '150,000',
    costOfManualEffortAED: '420,000',
    publishedDate: '12 Dec 2025',
    submittedBy: 'Khawla Al Ketbi',
    submittedDate: '9 Nov 2025',
  },
  {
    id: 'at-001b',
    domain: 'Exploration & Planning',
    level1: 'Exploration',
    level1Code: 'EXP',
    level2: 'Field Development Planning',
    level2Code: 'EXP.2',
    level3: 'Field Development Plan Preparation',
    level3Code: 'EXP.2.1',
    level4: 'Reservoir Data Compilation',
    level4Code: 'EXP.2.1.2',
    groupCompany: 'ADNOC Offshore',
    site: 'Das Island',
    status: 'Pending Signoff',
    processDescription: 'Compiling reservoir data from multiple field surveys',
    smeFeedback: '',
    processCriticality: 'Standard',
    numberOfPeopleInvolved: 'Medium (100-500)',
    scaleOfProcess: 'Medium: (bigger team within one department)',
    automationMaturityLevel: 'Semi-Automated',
    automationLevel: '40%',
    currentApplicationsSystems: ['Petrel', 'OpenWorks'],
    ongoingAutomation: 'Automated data import pipelines',
    businessRecommendation: 'Enhance with AI-based validation',
    keyChallenges: 'Data format inconsistencies across fields',
    aiPowered: 'No',
    aiPoweredUseCase: '',
    autonomousUseCaseEnabled: 'No',
    autonomousUseCaseDescription: '',
    processCycle: 'Quarterly',
    processRepetitionWithinCycle: '2',
    totalPersonnelFTE: '2.5',
    totalProcessDurationDays: '8',
    timeSpentManualPercent: '50%',
    dailyRateCardAED: '2,200',
    keyManualSteps: 'Data gathering, Format conversion, QC checks',
    annualCostOfManualEffortAED: '4,400,000.00000',
    northStarTarget: 'Fully Automated',
    targetAutomationLevelPercent: '85%',
    toBeAIPowered: 'No',
    toBeAIPoweredComments: '',
    rateCardAED: '120,000',
    costOfManualEffortAED: '300,000',
    publishedDate: '12 Dec 2025',
    submittedBy: 'Khawla Al Ketbi',
    submittedDate: '9 Nov 2025',
  },
  // ── Exploration & Planning  ▸ EXP.2.2 — Reservoir Simulation ────────────────
  {
    id: 'at-002',
    domain: 'Exploration & Planning',
    level1: 'Exploration',
    level1Code: 'EXP',
    level2: 'Field Development Planning',
    level2Code: 'EXP.2',
    level3: 'Reservoir Simulation',
    level3Code: 'EXP.2.2',
    level4: 'Model Calibration',
    level4Code: 'EXP.2.2.1',
    groupCompany: 'ADNOC Onshore',
    site: 'Habshan',
    status: 'In Progress',
    processDescription: 'Calibrating reservoir models using production history data',
    smeFeedback: '<p>Needs further evaluation from SME team</p>',
    processCriticality: 'Critical',
    numberOfPeopleInvolved: 'Medium (100-500)',
    scaleOfProcess: 'Large: (cross-department)',
    automationMaturityLevel: 'Manual',
    automationLevel: '10%',
    currentApplicationsSystems: ['Eclipse', 'MATLAB'],
    ongoingAutomation: 'None',
    businessRecommendation: 'Partial automation with AI',
    keyChallenges: 'Complex modeling requires human judgment',
    aiPowered: 'No',
    aiPoweredUseCase: '',
    autonomousUseCaseEnabled: 'No',
    autonomousUseCaseDescription: '',
    processCycle: 'Quarterly',
    processRepetitionWithinCycle: '2',
    totalPersonnelFTE: '5',
    totalProcessDurationDays: '30',
    timeSpentManualPercent: '85%',
    dailyRateCardAED: '3,200',
    keyManualSteps: 'Model setup, Parameter tuning, Validation runs',
    annualCostOfManualEffortAED: '8,320,000.00000',
    northStarTarget: 'Partially Automated',
    targetAutomationLevelPercent: '55%',
    toBeAIPowered: 'Yes',
    toBeAIPoweredComments: 'ML-based history matching',
    rateCardAED: '200,000',
    costOfManualEffortAED: '750,000',
    publishedDate: '',
    submittedBy: 'Khawla Al Ketbi',
    submittedDate: '20 Dec 2025',
  },
  // ── Drilling & Completions  ▸ DRL.1.1 — Well Design ─────────────────────────
  {
    id: 'at-003',
    domain: 'Drilling & Completions',
    level1: 'Drilling',
    level1Code: 'DRL',
    level2: 'Well Planning',
    level2Code: 'DRL.1',
    level3: 'Well Design',
    level3Code: 'DRL.1.1',
    level4: 'Casing Design',
    level4Code: 'DRL.1.1.1',
    groupCompany: 'ADNOC Drilling',
    site: 'General',
    status: 'Draft',
    processDescription: 'Designing optimal casing programs for well integrity',
    smeFeedback: '',
    processCriticality: 'Standard',
    numberOfPeopleInvolved: 'Low (1-100)',
    scaleOfProcess: 'Small: (single team)',
    automationMaturityLevel: 'Semi-Automated',
    automationLevel: '50%',
    currentApplicationsSystems: ['Landmark', 'WellPlan'],
    ongoingAutomation: 'Automated torque & drag calculations',
    businessRecommendation: 'Enhance existing automation',
    keyChallenges: 'Real-time data integration from rigs',
    aiPowered: 'Yes',
    aiPoweredUseCase: 'Predictive casing wear analysis',
    autonomousUseCaseEnabled: 'No',
    autonomousUseCaseDescription: '',
    processCycle: 'Per Well',
    processRepetitionWithinCycle: '1',
    totalPersonnelFTE: '2',
    totalProcessDurationDays: '5',
    timeSpentManualPercent: '40%',
    dailyRateCardAED: '1,800',
    keyManualSteps: 'Load analysis, Material selection',
    annualCostOfManualEffortAED: '1,314,000.00000',
    northStarTarget: 'Fully Automated',
    targetAutomationLevelPercent: '85%',
    toBeAIPowered: 'Yes',
    toBeAIPoweredComments: 'AI-optimized casing selection',
    rateCardAED: '100,000',
    costOfManualEffortAED: '280,000',
    publishedDate: '12 Dec 2025',
    submittedBy: 'Khawla Al Ketbi',
    submittedDate: '9 Nov 2025',
  },
  {
    id: 'at-003b',
    domain: 'Drilling & Completions',
    level1: 'Drilling',
    level1Code: 'DRL',
    level2: 'Well Planning',
    level2Code: 'DRL.1',
    level3: 'Well Design',
    level3Code: 'DRL.1.1',
    level4: 'Mud Weight Window Analysis',
    level4Code: 'DRL.1.1.2',
    groupCompany: 'ADNOC Drilling',
    site: 'General',
    status: 'Pending Signoff',
    processDescription: 'Determining safe mud weight operating windows for drilling',
    smeFeedback: '',
    processCriticality: 'Critical',
    numberOfPeopleInvolved: 'Low (1-100)',
    scaleOfProcess: 'Small: (single team)',
    automationMaturityLevel: 'Manual',
    automationLevel: '15%',
    currentApplicationsSystems: ['Landmark'],
    ongoingAutomation: 'None',
    businessRecommendation: 'Automate with geomechanical models',
    keyChallenges: 'Uncertain pore pressure data',
    aiPowered: 'No',
    aiPoweredUseCase: '',
    autonomousUseCaseEnabled: 'No',
    autonomousUseCaseDescription: '',
    processCycle: 'Per Well',
    processRepetitionWithinCycle: '1',
    totalPersonnelFTE: '1.5',
    totalProcessDurationDays: '3',
    timeSpentManualPercent: '70%',
    dailyRateCardAED: '2,000',
    keyManualSteps: 'Data collection, Modeling, Interpretation',
    annualCostOfManualEffortAED: '900,000.00000',
    northStarTarget: 'Fully Automated',
    targetAutomationLevelPercent: '90%',
    toBeAIPowered: 'Yes',
    toBeAIPoweredComments: 'AI pore pressure prediction from seismic',
    rateCardAED: '90,000',
    costOfManualEffortAED: '250,000',
    publishedDate: '12 Dec 2025',
    submittedBy: 'Khawla Al Ketbi',
    submittedDate: '9 Nov 2025',
  },
  // ── Production & Operations  ▸ PRD.1.1 — Flow Assurance ─────────────────────
  {
    id: 'at-004',
    domain: 'Production & Operations',
    level1: 'Production',
    level1Code: 'PRD',
    level2: 'Production Monitoring',
    level2Code: 'PRD.1',
    level3: 'Flow Assurance',
    level3Code: 'PRD.1.1',
    level4: 'Pipeline Integrity Monitoring',
    level4Code: 'PRD.1.1.1',
    groupCompany: 'ADNOC Gas',
    site: 'Ruwais',
    status: 'Returned Draft',
    processDescription: 'Monitoring pipeline integrity and corrosion rates in real time',
    smeFeedback: '<p>Pipeline monitoring should include corrosion analytics</p>',
    processCriticality: 'Critical',
    numberOfPeopleInvolved: 'High (500-1000)',
    scaleOfProcess: 'Large: (cross-department)',
    automationMaturityLevel: 'Automated',
    automationLevel: '70%',
    currentApplicationsSystems: ['OSIsoft PI', 'SCADA'],
    ongoingAutomation: 'Real-time pipeline monitoring dashboard',
    businessRecommendation: 'Enhance with predictive analytics',
    keyChallenges: 'Sensor data quality, network latency',
    aiPowered: 'Yes',
    aiPoweredUseCase: 'Corrosion rate prediction',
    autonomousUseCaseEnabled: 'Yes',
    autonomousUseCaseDescription: 'Auto shut-off on anomaly detection',
    processCycle: 'Continuous',
    processRepetitionWithinCycle: 'N/A',
    totalPersonnelFTE: '8',
    totalProcessDurationDays: '365',
    timeSpentManualPercent: '20%',
    dailyRateCardAED: '4,500',
    keyManualSteps: 'Manual inspection rounds, Report compilation',
    annualCostOfManualEffortAED: '13,140,000.00000',
    northStarTarget: 'Autonomous',
    targetAutomationLevelPercent: '95%',
    toBeAIPowered: 'Yes',
    toBeAIPoweredComments: 'Full predictive maintenance with AI',
    rateCardAED: '500,000',
    costOfManualEffortAED: '1,200,000',
    publishedDate: '',
    submittedBy: 'Khawla Al Ketbi',
    submittedDate: '20 Dec 2025',
  },
  // ── HSE & Compliance  ▸ HSE.1.1 — Incident Reporting ───────────────────────
  {
    id: 'at-005',
    domain: 'HSE & Compliance',
    level1: 'HSE Management',
    level1Code: 'HSE',
    level2: 'Incident Management',
    level2Code: 'HSE.1',
    level3: 'Incident Reporting',
    level3Code: 'HSE.1.1',
    level4: 'Near Miss Reporting',
    level4Code: 'HSE.1.1.1',
    groupCompany: 'ADNOC HQ',
    site: 'General',
    status: 'Published',
    processDescription: 'Capturing and classifying near-miss events across all sites',
    smeFeedback: '<p>Reporting process well-established but needs mobile support</p>',
    processCriticality: 'Standard',
    numberOfPeopleInvolved: 'Medium (100-500)',
    scaleOfProcess: 'Medium: (bigger team within one department)',
    automationMaturityLevel: 'Semi-Automated',
    automationLevel: '45%',
    currentApplicationsSystems: ['Enablon', 'SAP EHS'],
    ongoingAutomation: 'Mobile reporting app rollout',
    businessRecommendation: 'Mobile-first with auto-classification',
    keyChallenges: 'User adoption, offline capability',
    aiPowered: 'No',
    aiPoweredUseCase: '',
    autonomousUseCaseEnabled: 'No',
    autonomousUseCaseDescription: '',
    processCycle: 'Ad-hoc',
    processRepetitionWithinCycle: '~50/month',
    totalPersonnelFTE: '12',
    totalProcessDurationDays: '2',
    timeSpentManualPercent: '55%',
    dailyRateCardAED: '1,500',
    keyManualSteps: 'Form filling, Classification, Routing',
    annualCostOfManualEffortAED: '4,380,000.00000',
    northStarTarget: 'Fully Automated',
    targetAutomationLevelPercent: '80%',
    toBeAIPowered: 'Yes',
    toBeAIPoweredComments: 'NLP-based auto-classification of incidents',
    rateCardAED: '80,000',
    costOfManualEffortAED: '350,000',
    publishedDate: '12 Dec 2025',
    submittedBy: 'Khawla Al Ketbi',
    submittedDate: '9 Nov 2025',
  },
  {
    id: 'at-005b',
    domain: 'HSE & Compliance',
    level1: 'HSE Management',
    level1Code: 'HSE',
    level2: 'Incident Management',
    level2Code: 'HSE.1',
    level3: 'Incident Reporting',
    level3Code: 'HSE.1.1',
    level4: 'Root Cause Analysis',
    level4Code: 'HSE.1.1.2',
    groupCompany: 'ADNOC HQ',
    site: 'General',
    status: 'Pending Signoff',
    processDescription: 'Conducting root cause analysis for reported safety incidents',
    smeFeedback: '',
    processCriticality: 'Critical',
    numberOfPeopleInvolved: 'Low (1-100)',
    scaleOfProcess: 'Small: (single team)',
    automationMaturityLevel: 'Manual',
    automationLevel: '10%',
    currentApplicationsSystems: ['Enablon'],
    ongoingAutomation: 'None',
    businessRecommendation: 'AI-assisted root cause identification',
    keyChallenges: 'Requires domain expertise and contextual knowledge',
    aiPowered: 'No',
    aiPoweredUseCase: '',
    autonomousUseCaseEnabled: 'No',
    autonomousUseCaseDescription: '',
    processCycle: 'Per Incident',
    processRepetitionWithinCycle: '1',
    totalPersonnelFTE: '4',
    totalProcessDurationDays: '5',
    timeSpentManualPercent: '90%',
    dailyRateCardAED: '2,800',
    keyManualSteps: 'Evidence gathering, Analysis, Report writing',
    annualCostOfManualEffortAED: '2,016,000.00000',
    northStarTarget: 'Partially Automated',
    targetAutomationLevelPercent: '60%',
    toBeAIPowered: 'No',
    toBeAIPoweredComments: '',
    rateCardAED: '60,000',
    costOfManualEffortAED: '180,000',
    publishedDate: '12 Dec 2025',
    submittedBy: 'Khawla Al Ketbi',
    submittedDate: '9 Nov 2025',
  },
]
