import type { ProcessItem } from '@features/module-process-catalog/types'

export const CATALOG_DATA: ProcessItem[] = [
  {
    id: 'r1',
    domain: 'Exploration & Planning',
    level1Name: 'Exploration',
    level1Code: 'EXP.1',
    level2Name: 'Regional studies',
    level2Code: 'EXP.1.1',
    level3Name: 'Basin Modeling',
    level3Code: 'EXP.1.1.1',
    level3Status: 'Published',
    description: 'Creating a concept involves basin simulation and tectonic assessment.',
    isSharedService: true,
    entities: {
      'ADNOC HQ': { General: 'Yes', 'Site A': 'No', 'Site B': 'No' },
      'ADNOC AL DHAFRA AND AL YASAT': { General: 'No', 'Site A': 'No' },
    },
  },
  {
    id: 'r2',
    domain: 'Exploration & Planning',
    level1Name: 'Exploration',
    level1Code: 'EXP.1',
    level2Name: 'Regional studies',
    level2Code: 'EXP.1.1',
    level3Name: 'Geophysical data Interpretation (regional)',
    level3Code: 'EXP.1.1.2',
    level3Status: 'Published',
    description:
      'Geophysical data interpretation involves analyzing regional seismic surveys and well log data.',
    isSharedService: false,
    entities: {
      'ADNOC HQ': { General: 'No', 'Site A': 'No', 'Site B': 'No' },
      'ADNOC AL DHAFRA AND AL YASAT': { General: 'Yes', 'Site A': 'No' },
    },
  },
  {
    id: 'r3',
    domain: 'Exploration & Planning',
    level1Name: 'Exploration',
    level1Code: 'EXP.1',
    level2Name: 'Regional studies',
    level2Code: 'EXP.1.1',
    level3Name: 'Dashboard Exploration Test',
    level3Code: 'EXP.1.1.3',
    level3Status: 'Published',
    description: 'Evaluate exploration data using interactive dashboards for quick insights.',
    isSharedService: true,
    entities: {
      'ADNOC HQ': { General: 'No', 'Site A': 'No', 'Site B': 'No' },
      'ADNOC AL DHAFRA AND AL YASAT': { General: 'No', 'Site A': 'No' },
    },
  },
  {
    id: 'r4',
    domain: 'Exploration & Planning',
    level1Name: 'Exploration',
    level1Code: 'EXP.1',
    level2Name: 'Regional studies',
    level2Code: 'EXP.1.1',
    level3Name: 'Play-based exploration (concept)',
    level3Code: 'EXP.1.1.4',
    level3Status: 'Pending approval',
    description: 'Compiles and presents results of play assessments in a structured report format.',
    isSharedService: false,
    entities: {
      'ADNOC HQ': { General: 'No', 'Site A': 'No', 'Site B': 'No' },
      'ADNOC AL DHAFRA AND AL YASAT': { General: 'No', 'Site A': 'No' },
    },
  },
  {
    id: 'r5',
    domain: 'Exploration & Planning',
    level1Name: 'Exploration',
    level1Code: 'EXP.1',
    level2Name: 'Play Assessment (PA)',
    level2Code: 'EXP.1.2',
    level3Name: 'Project & Workflow Strategy (PA-01)',
    level3Code: 'EXP.1.2.1',
    level3Status: 'Published',
    description: 'Define project scope and workflow for efficient exploration.',
    isSharedService: true,
    entities: {
      'ADNOC HQ': { General: 'No', 'Site A': 'Yes', 'Site B': 'No' },
      'ADNOC AL DHAFRA AND AL YASAT': { General: 'No', 'Site A': 'No' },
    },
  },
  {
    id: 'r6',
    domain: 'Exploration & Planning',
    level1Name: 'Exploration',
    level1Code: 'EXP.1',
    level2Name: 'Play Assessment (PA)',
    level2Code: 'EXP.1.2',
    level3Name: 'Regional Data Gathering & QC (PA-02)',
    level3Code: 'EXP.1.2.2',
    level3Status: 'Published',
    description: 'Regional data gathering and QC involves collecting and validating regional data.',
    isSharedService: false,
    entities: {
      'ADNOC HQ': { General: 'No', 'Site A': 'No', 'Site B': 'No' },
      'ADNOC AL DHAFRA AND AL YASAT': { General: 'No', 'Site A': 'No' },
    },
  },
  {
    id: 'r7',
    domain: 'Exploration & Planning',
    level1Name: 'Exploration',
    level1Code: 'EXP.1',
    level2Name: 'Play Assessment (PA)',
    level2Code: 'EXP.1.2',
    level3Name: 'Play Evaluation Report (PA-05)',
    level3Code: 'EXP.1.2.5',
    level3Status: 'Published',
    description:
      'Documents play potential, risks, and key insights to support exploration decisions.',
    isSharedService: true,
    entities: {
      'ADNOC HQ': { General: 'No', 'Site A': 'Yes', 'Site B': 'No' },
      'ADNOC AL DHAFRA AND AL YASAT': { General: 'No', 'Site A': 'No' },
    },
  },
  {
    id: 'r8',
    domain: 'Exploration & Planning',
    level1Name: 'Field Development Planning',
    level1Code: 'EXP.2',
    level2Name: 'Subsurface Modeling',
    level2Code: 'EXP.2.1',
    level3Name: 'Detailed interpretation',
    level3Code: 'EXP.2.1.1',
    level3Status: 'Published',
    description: 'Performs detailed subsurface interpretation to refine geological understanding.',
    isSharedService: true,
    entities: {
      'ADNOC HQ': { General: 'No', 'Site A': 'No', 'Site B': 'No' },
      'ADNOC AL DHAFRA AND AL YASAT': { General: 'No', 'Site A': 'No' },
    },
  },
  {
    id: 'r9',
    domain: 'Exploration & Planning',
    level1Name: 'Field Development Planning',
    level1Code: 'EXP.2',
    level2Name: 'Subsurface Modeling',
    level2Code: 'EXP.2.1',
    level3Name: 'Geological modeling',
    level3Code: 'EXP.2.1.2',
    level3Status: 'Published',
    description: 'Builds geological models to represent subsurface structures and formations.',
    isSharedService: true,
    entities: {
      'ADNOC HQ': { General: 'No', 'Site A': 'No', 'Site B': 'No' },
      'ADNOC AL DHAFRA AND AL YASAT': { General: 'No', 'Site A': 'Yes' },
    },
  },
]
