import type { TaskItem } from '@features/module-process-catalog/types/my-tasks'
import { withSubRows } from '@features/module-process-catalog/types/my-tasks'

export const MY_TASKS: TaskItem[] = [
  withSubRows({
    id: 'task-1',
    processName: 'Regional studies',
    requestId: '9377353',
    level: 'L 3',
    domain: 'Corporate Communications',
    stageCurrent: 1,
    stageTotal: 3,
    stageText: 'Pending updates',
    requester: 'Maryam Al Shamsi',
    status: 'Returned draft',
    returnComment: 'Please revise section 2',
    returnedBy: 'Ahmed Al Mansoori',
    actionRequired: 'Review and update',
    submittedOn: '08 Apr 2024',
    changes: [
      { name: 'Process creation', changeType: 'Create', oldValue: '-', newValue: 'L3 created' },
      {
        name: 'Process name',
        changeType: 'Update',
        oldValue: '-',
        newValue: 'Play-based exploration (concept) 2 (Dashboard)',
      },
      {
        name: 'Process hierarchy',
        changeType: 'Update',
        oldValue: '-',
        newValue: 'Domain / Exploration & Planning',
      },
      {
        name: 'Process hierarchy',
        changeType: 'Update',
        oldValue: '-',
        newValue: 'L1 / Exploration',
      },
      {
        name: 'Process hierarchy',
        changeType: 'Update',
        oldValue: '-',
        newValue: 'L2 / Regional studies',
      },
      {
        name: 'Process description',
        changeType: 'Update',
        oldValue: '-',
        newValue: 'Creating a comprehensive Basin Modeling concept i...',
      },
      {
        name: 'Process parent name (L2)',
        changeType: 'Update',
        oldValue: 'Regional studies',
        newValue: 'Studies',
      },
    ],
  }),
  withSubRows({
    id: 'task-2',
    processName: 'Define Budget and Schedule',
    requestId: '9377354',
    level: 'L 3',
    domain: 'Corporate Communications',
    stageCurrent: 1,
    stageTotal: 3,
    stageText: 'Pending updates',
    requester: 'Maryam Al Shamsi',
    status: 'Returned draft',
    returnComment: 'Budget figures need review',
    returnedBy: 'Sara Al Mazrouei',
    actionRequired: 'Re-submit with corrections',
    submittedOn: '14 Jan 2026',
    changes: [
      { name: 'Budget Plan', changeType: 'Edit', oldValue: '1,200,000', newValue: '1,500,000' },
      { name: 'Schedule', changeType: 'Update', oldValue: 'Q1 2026', newValue: 'Q2 2026' },
    ],
  }),
  withSubRows({
    id: 'task-3',
    processName: 'Develop external communication',
    requestId: '9377355',
    level: 'L 3',
    domain: 'Corporate Communications',
    stageCurrent: 1,
    stageTotal: 3,
    stageText: 'Pending updates',
    requester: 'Maryam Al Shamsi',
    status: 'Returned draft',
    returnComment: 'Tone needs adjustment',
    returnedBy: 'Khalid Al Hamadi',
    actionRequired: 'Revise communication plan',
    submittedOn: '15 Jan 2026',
    changes: [{ name: 'Comm. Plan', changeType: 'Edit', oldValue: 'V1', newValue: 'V2' }],
  }),
  withSubRows({
    id: 'task-4',
    processName: 'Prepare media materials',
    requestId: '9377356',
    level: 'L 3',
    domain: 'Corporate Communications',
    stageCurrent: 1,
    stageTotal: 3,
    stageText: 'Pending updates',
    requester: 'Maryam Al Shamsi',
    status: 'Returned draft',
    returnComment: 'Missing brand guidelines',
    returnedBy: 'Noura Al Dhaheri',
    actionRequired: 'Attach brand assets',
    submittedOn: '16 Jan 2026',
    changes: [{ name: 'Media Pack', changeType: 'Addition', oldValue: '—', newValue: 'Attached' }],
  }),
  withSubRows({
    id: 'task-5',
    processName: 'Defining brand performance',
    requestId: '9377357',
    level: 'L 3',
    domain: 'Corporate Communications',
    stageCurrent: 1,
    stageTotal: 3,
    stageText: 'Pending updates',
    requester: 'Maryam Al Shamsi',
    status: 'Returned draft',
    returnComment: 'KPIs not aligned',
    returnedBy: 'Omar Al Ketbi',
    actionRequired: 'Align KPIs with strategy',
    submittedOn: '17 Jan 2026',
    changes: [
      { name: 'KPI Dashboard', changeType: 'Edit', oldValue: 'Q3 Target', newValue: 'Q4 Target' },
    ],
  }),
]
