import type { RequestItem } from '@features/module-process-catalog/types/submitted-requests'

export const SUBMITTED_REQUESTS: RequestItem[] = [
  {
    id: 'request-1',
    processName: 'Play-based exploration',
    requestId: '9377353',
    level: 'L 3',
    requester: 'Maryam Al Shamsi',
    approver: 'Khaled Al Mansoori',
    status: 'Pending approval',
    stageCurrent: 2,
    stageTotal: 3,
    stageText: 'Pending custodian approval',
    submittedOn: '08 Apr 2024',
    publishedOn: '-',
    changes: [
      {
        id: 'description',
        label: 'Process description',
        oldValue: '-',
        newValue: 'Creating a communication plan',
      },
      {
        id: 'parent-name',
        label: 'Process parent name (L2)',
        oldValue: 'Regional studies',
        newValue: 'Studies',
      },
      {
        id: 'applicability',
        label: 'Applicability',
        oldValue: 'ADNOC - Onshore',
        newValue: 'ADNOC - Offshore',
      },
      { id: 'shared-service', label: 'Shared service', oldValue: 'No', newValue: 'Yes' },
    ],
  },
  {
    id: 'request-2',
    processName: 'Define Budget and Schedule',
    requestId: '9377353',
    level: 'L 3',
    requester: 'Mohammed Al Hajeri',
    approver: 'Khaled Al Mansoori',
    status: 'Returned draft',
    stageCurrent: 1,
    stageTotal: 3,
    stageText: 'Pending updates',
    submittedOn: '09 Apr 2024',
    publishedOn: '-',
    changes: [
      {
        id: 'description',
        label: 'Process description',
        oldValue: 'Draft description',
        newValue: 'Updated process scope',
      },
      {
        id: 'parent-name',
        label: 'Process parent name (L2)',
        oldValue: 'Planning',
        newValue: 'Budget planning',
      },
      {
        id: 'applicability',
        label: 'Applicability',
        oldValue: 'Corporate',
        newValue: 'Corporate + Group',
      },
      { id: 'shared-service', label: 'Shared service', oldValue: 'No', newValue: 'No' },
    ],
  },
  {
    id: 'request-3',
    processName: 'Develop external communication',
    requestId: '9377353',
    level: 'L 3',
    requester: 'Noura Al Ghamdi',
    approver: 'Khaled Al Mansoori',
    status: 'Pending signoff',
    stageCurrent: 3,
    stageTotal: 3,
    stageText: 'Program manager signoff',
    submittedOn: '10 Apr 2024',
    publishedOn: '-',
    changes: [
      {
        id: 'description',
        label: 'Process description',
        oldValue: 'External comms draft',
        newValue: 'External comms final',
      },
      {
        id: 'parent-name',
        label: 'Process parent name (L2)',
        oldValue: 'Campaign management',
        newValue: 'Comms management',
      },
      {
        id: 'applicability',
        label: 'Applicability',
        oldValue: 'Internal',
        newValue: 'Internal + External',
      },
      { id: 'shared-service', label: 'Shared service', oldValue: 'Yes', newValue: 'Yes' },
    ],
  },
  {
    id: 'request-4',
    processName: 'Prepare media materials',
    requestId: '9377353',
    level: 'L 3',
    requester: 'Maryam Al Shamsi',
    approver: 'Khaled Al Mansoori',
    status: 'Pending approval',
    stageCurrent: 2,
    stageTotal: 3,
    stageText: 'Pending custodian approval',
    submittedOn: '07 Apr 2024',
    publishedOn: '-',
    changes: [
      {
        id: 'description',
        label: 'Process description',
        oldValue: 'Media draft',
        newValue: 'Media delivery package',
      },
      {
        id: 'parent-name',
        label: 'Process parent name (L2)',
        oldValue: 'Operations',
        newValue: 'Media operations',
      },
      {
        id: 'applicability',
        label: 'Applicability',
        oldValue: 'ADNOC HQ',
        newValue: 'All entities',
      },
      { id: 'shared-service', label: 'Shared service', oldValue: 'No', newValue: 'Yes' },
    ],
  },
  {
    id: 'request-5',
    processName: 'Defining brand performance',
    requestId: '9377353',
    level: 'L 3',
    requester: 'Noura Al Ghamdi',
    approver: 'Khaled Al Mansoori',
    status: 'Published',
    stageCurrent: 3,
    stageTotal: 3,
    stageText: 'Program manager signoff',
    submittedOn: '06 Apr 2024',
    publishedOn: '13 May 2024',
    changes: [
      {
        id: 'description',
        label: 'Process description',
        oldValue: 'Brand KPI process',
        newValue: 'Brand performance framework',
      },
      {
        id: 'parent-name',
        label: 'Process parent name (L2)',
        oldValue: 'Branding',
        newValue: 'Brand strategy',
      },
      {
        id: 'applicability',
        label: 'Applicability',
        oldValue: 'Marketing',
        newValue: 'Corporate communications',
      },
      { id: 'shared-service', label: 'Shared service', oldValue: 'No', newValue: 'Yes' },
    ],
  },
]
