import type { Opportunity } from '../types'

export const OPPORTUNITIES_DATA: Opportunity[] = [
  {
    id: 'opp-001',
    name: 'Continuous Control Monitoring System',
    code: 'EXP.1.1.1',
    domain: 'Audit & Assurance',
    gcOwner: 'ADNOC HQ',
    applicability: { proposedTo: 4, acceptedBy: 2 },
    status: 'Draft',
    workflowStatus: 'Proposed',
    description:
      'Implement a continuous control monitoring system to automate audit and compliance checks across all business units.',
    functionalCapabilities:
      'Automated control testing, real-time dashboards, exception escalation workflows',
    keyPrerequisites:
      'Defined control framework, ERP data access, IT infrastructure for automation',
    keyBusinessBenefits:
      'Reduces manual audit hours by 60%, accelerates detection of control failures',
    solutionType: 'Process Automation',
    illustrativePlatform: 'RPA (UiPath), SAP GRC, Power BI',
    aiApplicability: 'Yes',
    impactedBusinessProcesses: 'Internal Audit, Compliance Management, Risk Assessment',
    estimatedImplementationDuration: 9,
    estimatedImplementationCost: 2500000,
    proposedPriority: 'High',
    effortManDays: 'High',
    investmentCost: 'High',
    riskLevel: 'Medium',
    technicalDifficulty: 'High',
    resourceRequirements: 'High',
    costSavingRevenuePotential: 'High',
    customerSatisfactionIncrease: 'High',
    businessRiskReduction: 'High',
    efficiencyImprovement: 'High',
    impactType: 'Cost Reduction',
    impactReason: 'Manual Process Elimination',
    drivers: 'Regulatory compliance, operational efficiency',
    costValueEstimationAssumptions:
      '5 FTEs at AED 240K/year, 60% time saving realised post go-live',
    comments: 'Priority initiative aligned with internal audit modernisation roadmap',
  },
  {
    id: 'opp-002',
    name: 'Integration of Digital Tools with Architecture',
    code: 'EXP.1.1.2',
    domain: 'Audit & Assurance',
    gcOwner: 'ADNOC HQ',
    applicability: { proposedTo: 6, acceptedBy: 3 },
    status: 'Draft',
    workflowStatus: 'Proposed',
    description:
      'Integrate existing digital tools with enterprise architecture to streamline data flows and reduce manual reconciliation.',
    functionalCapabilities: 'API-based integration, unified data layer, automated reconciliation',
    keyPrerequisites: 'Enterprise architecture documentation, API readiness of existing tools',
    keyBusinessBenefits: 'Eliminates data silos, reduces reconciliation effort by 40%',
    solutionType: 'Integration',
    illustrativePlatform: 'API Integration, Middleware (MuleSoft)',
    aiApplicability: 'Possible',
    impactedBusinessProcesses: 'Data Management, Reporting, Financial Reconciliation',
    estimatedImplementationDuration: 5,
    estimatedImplementationCost: 1500000,
    proposedPriority: 'Medium',
    effortManDays: 'Medium',
    investmentCost: 'Medium',
    riskLevel: 'Low',
    technicalDifficulty: 'Medium',
    resourceRequirements: 'Medium',
    costSavingRevenuePotential: 'Medium',
    customerSatisfactionIncrease: 'Medium',
    businessRiskReduction: 'Medium',
    efficiencyImprovement: 'Medium',
    impactType: 'Efficiency',
    impactReason: 'Integration & Automation',
    drivers: 'Data quality, operational efficiency',
    costValueEstimationAssumptions: '90 man-days at AED 1,500/day blended rate',
    comments: 'Dependency on enterprise architecture team availability for design phase',
  },
  {
    id: 'opp-003',
    name: 'Automated Time Tracking & Reporting',
    code: 'EXP.1.1.3',
    domain: 'Audit & Assurance',
    gcOwner: 'ADNOC HQ',
    applicability: { proposedTo: 2, acceptedBy: 0 },
    status: 'Draft',
    workflowStatus: 'Proposed',
    description:
      'Automate time tracking and reporting processes to eliminate manual data entry and improve accuracy of resource utilization reports.',
    functionalCapabilities:
      'Automated timesheets, resource utilization dashboards, variance alerts',
    keyPrerequisites: 'HR system integration, employee digital access',
    keyBusinessBenefits: 'Eliminates manual data entry errors, improves resource planning accuracy',
    solutionType: 'Process Automation',
    illustrativePlatform: 'RPA (Power Automate)',
    aiApplicability: 'Yes',
    impactedBusinessProcesses: 'Resource Management, Payroll, Project Reporting',
    estimatedImplementationDuration: 2,
    estimatedImplementationCost: 800000,
    proposedPriority: 'Medium',
    effortManDays: 'Low',
    investmentCost: 'Low',
    riskLevel: 'Low',
    technicalDifficulty: 'Low',
    resourceRequirements: 'Low',
    costSavingRevenuePotential: 'Medium',
    customerSatisfactionIncrease: 'High',
    businessRiskReduction: 'Medium',
    efficiencyImprovement: 'High',
    impactType: 'Cost Reduction',
    impactReason: 'Manual Process Elimination',
    drivers: 'Operational efficiency, data accuracy',
    costValueEstimationAssumptions:
      '30 man-days at AED 1,200/day; 2 FTE hours/week saved across 200 staff',
    comments: 'Quick win opportunity; can be delivered within one quarter',
  },
  {
    id: 'opp-004',
    name: 'Audit Committee Management and Reporting',
    code: 'EXP.1.1.4',
    domain: 'Audit & Assurance',
    gcOwner: 'ADNOC HQ',
    applicability: { proposedTo: 0, acceptedBy: 0 },
    status: 'Draft',
    workflowStatus: 'Proposed',
    description:
      'Build a centralized audit committee management platform with automated meeting scheduling, document distribution, and reporting.',
    functionalCapabilities:
      'Meeting scheduling, document management, automated agenda generation, minutes tracking',
    keyPrerequisites: 'Governance framework alignment, SharePoint or intranet infrastructure',
    keyBusinessBenefits:
      'Reduces committee preparation time by 50%, ensures timely document distribution',
    solutionType: 'Document & Workflow Management',
    illustrativePlatform: 'SharePoint, Power Automate',
    aiApplicability: 'Yes',
    impactedBusinessProcesses: 'Governance, Audit Management, Board Reporting',
    estimatedImplementationDuration: 5,
    estimatedImplementationCost: 1200000,
    proposedPriority: 'High',
    effortManDays: 'Medium',
    investmentCost: 'Medium',
    riskLevel: 'Low',
    technicalDifficulty: 'Medium',
    resourceRequirements: 'Medium',
    costSavingRevenuePotential: 'Medium',
    customerSatisfactionIncrease: 'High',
    businessRiskReduction: 'High',
    efficiencyImprovement: 'High',
    impactType: 'Governance',
    impactReason: 'Workflow Digitisation',
    drivers: 'Corporate governance, compliance reporting',
    costValueEstimationAssumptions:
      '90 man-days; SharePoint licensing included in existing O365 agreement',
    comments: 'Governance team sign-off required before requirements finalisation',
  },
  {
    id: 'opp-005',
    name: 'Leverage ADNOC Group Existing Audit Infrastructure',
    code: 'EXP.1.2.1',
    domain: 'Audit & Assurance',
    gcOwner: 'ADNOC HQ',
    applicability: { proposedTo: 3, acceptedBy: 1 },
    status: 'Draft',
    workflowStatus: 'Proposed',
    description:
      'Leverage existing audit infrastructure across ADNOC Group to create synergies and reduce duplication of audit activities.',
    functionalCapabilities:
      'Shared audit repository, cross-entity coordination, centralized reporting',
    keyPrerequisites: 'Data-sharing agreements, access governance framework, network connectivity',
    keyBusinessBenefits:
      'Eliminates duplicate audit activities, reduces group-wide audit costs by 25%',
    solutionType: 'Platform Consolidation',
    illustrativePlatform: 'Data Integration, Analytics (Power BI, Tableau)',
    aiApplicability: 'Yes',
    impactedBusinessProcesses: 'Group Audit, Risk Management, Compliance',
    estimatedImplementationDuration: 9,
    estimatedImplementationCost: 3000000,
    proposedPriority: 'High',
    effortManDays: 'High',
    investmentCost: 'High',
    riskLevel: 'Medium',
    technicalDifficulty: 'High',
    resourceRequirements: 'High',
    costSavingRevenuePotential: 'High',
    customerSatisfactionIncrease: 'Medium',
    businessRiskReduction: 'High',
    efficiencyImprovement: 'Medium',
    impactType: 'Cost Reduction',
    impactReason: 'Platform Consolidation',
    drivers: 'Group synergies, audit efficiency',
    costValueEstimationAssumptions:
      'Based on 8 FTE audit redundancies across 5 entities at AED 250K/year',
    comments: 'Requires data-sharing agreements with all participating group entities',
  },
  {
    id: 'opp-006',
    name: 'Automated Risk Assessment',
    code: 'EXP.1.2.2',
    domain: 'Audit & Assurance',
    gcOwner: 'ADNOC HQ',
    applicability: { proposedTo: 3, acceptedBy: 1 },
    status: 'Draft',
    workflowStatus: 'Proposed',
    description:
      'Develop an automated risk assessment engine using AI/ML to identify, score, and prioritize risks across business processes.',
    functionalCapabilities:
      'Risk scoring engine, automated risk register updates, risk heatmap visualization',
    keyPrerequisites: 'Historical risk data, defined risk taxonomy, ML infrastructure',
    keyBusinessBenefits:
      'Reduces risk assessment cycle from 4 weeks to 3 days, improves risk coverage',
    solutionType: 'AI/ML Solution',
    illustrativePlatform: 'AI/ML (Azure ML), Analytics Platform',
    aiApplicability: 'Yes',
    impactedBusinessProcesses: 'Risk Management, Internal Audit, Compliance',
    estimatedImplementationDuration: 9,
    estimatedImplementationCost: 4000000,
    proposedPriority: 'High',
    effortManDays: 'High',
    investmentCost: 'High',
    riskLevel: 'Medium',
    technicalDifficulty: 'High',
    resourceRequirements: 'High',
    costSavingRevenuePotential: 'High',
    customerSatisfactionIncrease: 'High',
    businessRiskReduction: 'High',
    efficiencyImprovement: 'High',
    impactType: 'Risk Reduction',
    impactReason: 'AI/ML Implementation',
    drivers: 'Enterprise risk management, digital transformation',
    costValueEstimationAssumptions: '2 ML engineers for 9 months; cloud compute at AED 120K/year',
    comments: 'Model retraining schedule must be defined as part of the solution design',
  },
  {
    id: 'opp-007',
    name: 'Portfolio Management Automation and Reporting',
    code: 'EXP.1.2.3',
    domain: 'Audit & Assurance',
    gcOwner: 'ADNOC HQ',
    applicability: { proposedTo: 1, acceptedBy: 0 },
    status: 'Draft',
    workflowStatus: 'Proposed',
    description:
      'Automate portfolio management processes including tracking, reporting, and performance analysis across all investment portfolios.',
    functionalCapabilities: 'Portfolio dashboard, automated performance reports, variance analysis',
    keyPrerequisites: 'Defined portfolio KPIs, data feeds from financial systems',
    keyBusinessBenefits: 'Reduces reporting effort by 50%, enables real-time portfolio visibility',
    solutionType: 'Analytics & Reporting',
    illustrativePlatform: 'Power BI, Power Automate',
    aiApplicability: 'Yes',
    impactedBusinessProcesses: 'Investment Management, Financial Reporting, Executive Governance',
    estimatedImplementationDuration: 5,
    estimatedImplementationCost: 1500000,
    proposedPriority: 'Medium',
    effortManDays: 'Medium',
    investmentCost: 'Medium',
    riskLevel: 'Low',
    technicalDifficulty: 'Medium',
    resourceRequirements: 'Medium',
    costSavingRevenuePotential: 'Medium',
    customerSatisfactionIncrease: 'High',
    businessRiskReduction: 'High',
    efficiencyImprovement: 'Medium',
    impactType: 'Efficiency',
    impactReason: 'Platform Consolidation',
    drivers: 'Investment oversight, strategic reporting',
    costValueEstimationAssumptions: '90 man-days; existing Power BI licensing covers delivery',
    comments: 'KPI definitions require alignment with CFO office before development starts',
  },
  {
    id: 'opp-008',
    name: 'Custom Cloud-Based Capital Management System',
    code: 'EXP.1.3.1',
    domain: 'Audit & Assurance',
    gcOwner: 'ADNOC HQ',
    applicability: { proposedTo: 2, acceptedBy: 0 },
    status: 'Draft',
    workflowStatus: 'Proposed',
    description:
      'Design and implement a cloud-based capital management system tailored to ADNOC Group needs for improved capital allocation and tracking.',
    functionalCapabilities:
      'Capital allocation engine, project budgeting, spend tracking, forecasting',
    keyPrerequisites:
      'Cloud infrastructure readiness, defined capital planning process, ERP integration',
    keyBusinessBenefits: 'Real-time capital visibility, 30% reduction in budget overruns',
    solutionType: 'Cloud Platform',
    illustrativePlatform: 'Cloud ERP (SAP S/4HANA), Azure',
    aiApplicability: 'Yes',
    impactedBusinessProcesses: 'Capital Planning, Project Management, Financial Control',
    estimatedImplementationDuration: 14,
    estimatedImplementationCost: 5000000,
    proposedPriority: 'High',
    effortManDays: 'High',
    investmentCost: 'High',
    riskLevel: 'High',
    technicalDifficulty: 'High',
    resourceRequirements: 'High',
    costSavingRevenuePotential: 'High',
    customerSatisfactionIncrease: 'High',
    businessRiskReduction: 'Medium',
    efficiencyImprovement: 'High',
    impactType: 'Revenue Generation',
    impactReason: 'AI/ML Implementation',
    drivers: 'Capital efficiency, strategic growth',
    costValueEstimationAssumptions:
      'SAP S/4HANA licensing + 180 man-days implementation; 30% overrun prevention value',
    comments: 'Requires executive sponsorship from CFO; cloud migration governance approval needed',
  },
  {
    id: 'opp-009',
    name: 'Automated Capital Project Budgeting',
    code: 'EXP.1.3.2',
    domain: 'Audit & Assurance',
    gcOwner: 'ADNOC HQ',
    applicability: { proposedTo: 6, acceptedBy: 3 },
    status: 'Draft',
    workflowStatus: 'Proposed',
    description:
      'Automate the capital project budgeting process from initiation through approval using workflow automation and real-time dashboards.',
    functionalCapabilities:
      'Automated budget requests, approval workflows, real-time cost dashboards',
    keyPrerequisites:
      'SAP integration, defined approval hierarchy, project classification taxonomy',
    keyBusinessBenefits: 'Reduces budgeting cycle by 3 weeks, improves approval transparency',
    solutionType: 'Process Automation',
    illustrativePlatform: 'SAP, RPA (Power Automate)',
    aiApplicability: 'Yes',
    impactedBusinessProcesses: 'Capital Budgeting, Project Governance, Finance',
    estimatedImplementationDuration: 5,
    estimatedImplementationCost: 2000000,
    proposedPriority: 'Medium',
    effortManDays: 'Medium',
    investmentCost: 'Medium',
    riskLevel: 'Medium',
    technicalDifficulty: 'Medium',
    resourceRequirements: 'Medium',
    costSavingRevenuePotential: 'Medium',
    customerSatisfactionIncrease: 'High',
    businessRiskReduction: 'High',
    efficiencyImprovement: 'Medium',
    impactType: 'Efficiency',
    impactReason: 'Integration & Automation',
    drivers: 'Capital governance, budget accuracy',
    costValueEstimationAssumptions: '90 man-days; leverages existing SAP investment',
    comments: 'Approval hierarchy must be formally defined and signed off by Finance',
  },
  {
    id: 'opp-010',
    name: 'AI-Driven Historical Data Automation',
    code: 'EXP.1.3.3',
    domain: 'Audit & Assurance',
    gcOwner: 'ADNOC HQ',
    applicability: { proposedTo: 5, acceptedBy: 2 },
    status: 'Draft',
    workflowStatus: 'Proposed',
    description:
      'Implement AI-driven automation to extract, transform, and load historical data from legacy systems into modern analytical platforms.',
    functionalCapabilities:
      'Intelligent data extraction, automated ETL, data quality validation, historical analytics',
    keyPrerequisites: 'Legacy system access, data lake infrastructure, data governance framework',
    keyBusinessBenefits: 'Unlocks historical insights, reduces data preparation time by 70%',
    solutionType: 'AI/ML Solution',
    illustrativePlatform: 'AI/ML (Azure ML), Data Lake (Azure Data Lake)',
    aiApplicability: 'Yes',
    impactedBusinessProcesses: 'Data Management, Analytics, Legacy Modernization',
    estimatedImplementationDuration: 9,
    estimatedImplementationCost: 3500000,
    proposedPriority: 'High',
    effortManDays: 'High',
    investmentCost: 'High',
    riskLevel: 'Medium',
    technicalDifficulty: 'High',
    resourceRequirements: 'High',
    costSavingRevenuePotential: 'High',
    customerSatisfactionIncrease: 'High',
    businessRiskReduction: 'Medium',
    efficiencyImprovement: 'High',
    impactType: 'Efficiency',
    impactReason: 'Cost Optimization',
    drivers: 'Data modernization, analytical capability',
    costValueEstimationAssumptions: '180 man-days; Azure Data Lake subscription at AED 180K/year',
    comments: 'Data governance policy must be established before migration commences',
  },
  {
    id: 'opp-011',
    name: 'Real-time Monitoring and Predictive Analytics',
    code: 'EXP.1.4.1',
    domain: 'Audit & Assurance',
    gcOwner: 'ADNOC HQ',
    applicability: { proposedTo: 5, acceptedBy: 2 },
    status: 'Draft',
    workflowStatus: 'Proposed',
    description:
      'Deploy real-time monitoring infrastructure with predictive analytics capabilities to proactively identify operational risks and inefficiencies.',
    functionalCapabilities:
      'Real-time sensor data ingestion, predictive alerts, operational dashboards',
    keyPrerequisites:
      'IoT sensor deployment, data streaming infrastructure, ML model training data',
    keyBusinessBenefits:
      'Prevents unplanned downtime, reduces operational losses by AED 2.5M annually',
    solutionType: 'IoT & Analytics',
    illustrativePlatform: 'IoT (Azure IoT Hub), AI/ML (Azure ML)',
    aiApplicability: 'Yes',
    impactedBusinessProcesses: 'Operations, Asset Management, Risk Monitoring',
    estimatedImplementationDuration: 9,
    estimatedImplementationCost: 5500000,
    proposedPriority: 'High',
    effortManDays: 'High',
    investmentCost: 'High',
    riskLevel: 'Medium',
    technicalDifficulty: 'High',
    resourceRequirements: 'High',
    costSavingRevenuePotential: 'High',
    customerSatisfactionIncrease: 'High',
    businessRiskReduction: 'High',
    efficiencyImprovement: 'High',
    impactType: 'Risk Reduction',
    impactReason: 'Workflow Digitisation',
    drivers: 'Asset reliability, operational continuity',
    costValueEstimationAssumptions:
      'IoT sensor deployment at AED 1.2M; Azure IoT subscription AED 300K/year',
    comments: 'IoT sensor installation requires physical access coordination with operations',
  },
  {
    id: 'opp-012',
    name: 'Smart Contract Management System',
    code: 'EXP.1.4.2',
    domain: 'Audit & Assurance',
    gcOwner: 'ADNOC HQ',
    applicability: { proposedTo: 4, acceptedBy: 2 },
    status: 'Draft',
    workflowStatus: 'Proposed',
    description:
      'Build a smart contract management system to automate contract creation, approval workflows, and compliance monitoring.',
    functionalCapabilities:
      'Contract authoring, automated clause review, approval workflow, obligation tracking',
    keyPrerequisites: 'Legal team involvement, contract data repository, CLM platform procurement',
    keyBusinessBenefits: 'Reduces contract cycle time by 40%, improves compliance monitoring',
    solutionType: 'Document & Workflow Management',
    illustrativePlatform: 'CLM Platform (Icertis), AI/ML',
    aiApplicability: 'Yes',
    impactedBusinessProcesses: 'Legal, Procurement, Compliance',
    estimatedImplementationDuration: 5,
    estimatedImplementationCost: 2000000,
    proposedPriority: 'Medium',
    effortManDays: 'Medium',
    investmentCost: 'High',
    riskLevel: 'Low',
    technicalDifficulty: 'Medium',
    resourceRequirements: 'Medium',
    costSavingRevenuePotential: 'High',
    customerSatisfactionIncrease: 'High',
    businessRiskReduction: 'High',
    efficiencyImprovement: 'Medium',
    impactType: 'Efficiency',
    impactReason: 'Integration & Automation',
    drivers: 'Contract risk management, procurement efficiency',
    costValueEstimationAssumptions: 'Icertis licensing AED 600K/year; 90 man-days implementation',
    comments: 'Legal team must validate AI clause extraction accuracy before go-live',
  },
  {
    id: 'opp-013',
    name: 'Digital Compliance Tracker',
    code: 'EXP.1.4.3',
    domain: 'Audit & Assurance',
    gcOwner: 'ADNOC HQ',
    applicability: { proposedTo: 3, acceptedBy: 1 },
    status: 'Draft',
    workflowStatus: 'Proposed',
    description:
      'Develop a digital compliance tracking system to monitor regulatory requirements, deadlines, and obligations across all entities.',
    functionalCapabilities:
      'Regulatory obligation register, deadline alerts, compliance status dashboard',
    keyPrerequisites: 'Regulatory inventory, compliance ownership mapping, GRC platform',
    keyBusinessBenefits:
      'Zero missed regulatory deadlines, 30% reduction in compliance management effort',
    solutionType: 'GRC Platform',
    illustrativePlatform: 'GRC Platform (ServiceNow GRC), NLP',
    aiApplicability: 'Possible',
    impactedBusinessProcesses: 'Compliance Management, Legal, Regulatory Affairs',
    estimatedImplementationDuration: 5,
    estimatedImplementationCost: 1800000,
    proposedPriority: 'Medium',
    effortManDays: 'Medium',
    investmentCost: 'Medium',
    riskLevel: 'Low',
    technicalDifficulty: 'Medium',
    resourceRequirements: 'Medium',
    costSavingRevenuePotential: 'Medium',
    customerSatisfactionIncrease: 'High',
    businessRiskReduction: 'High',
    efficiencyImprovement: 'High',
    impactType: 'Risk Reduction',
    impactReason: 'Compliance & Governance',
    drivers: 'Regulatory compliance, governance',
    costValueEstimationAssumptions:
      'ServiceNow GRC licensing AED 400K/year; 90 man-days implementation',
    comments:
      'NLP regulatory monitoring module requires internet connectivity and legal validation',
  },
  {
    id: 'opp-014',
    name: 'Automated Vendor Assessment',
    code: 'EXP.1.5.1',
    domain: 'Audit & Assurance',
    gcOwner: 'ADNOC HQ',
    applicability: { proposedTo: 2, acceptedBy: 0 },
    status: 'Draft',
    workflowStatus: 'Proposed',
    description:
      'Automate vendor assessment and due diligence processes including financial checks, compliance verifications, and performance scoring.',
    functionalCapabilities:
      'Automated vendor scoring, third-party data enrichment, compliance verification',
    keyPrerequisites: 'Vendor master data, third-party API access, defined scoring criteria',
    keyBusinessBenefits: 'Reduces vendor onboarding time by 60%, standardizes risk assessment',
    solutionType: 'Process Automation',
    illustrativePlatform: 'RPA, Third-party APIs (Dun & Bradstreet)',
    aiApplicability: 'Yes',
    impactedBusinessProcesses: 'Procurement, Vendor Management, Compliance',
    estimatedImplementationDuration: 2,
    estimatedImplementationCost: 1000000,
    proposedPriority: 'Medium',
    effortManDays: 'Low',
    investmentCost: 'Low',
    riskLevel: 'Low',
    technicalDifficulty: 'Low',
    resourceRequirements: 'Low',
    costSavingRevenuePotential: 'Low',
    customerSatisfactionIncrease: 'Medium',
    businessRiskReduction: 'Medium',
    efficiencyImprovement: 'High',
    impactType: 'Risk Reduction',
    impactReason: 'Predictive Analytics',
    drivers: 'Vendor risk management, procurement efficiency',
    costValueEstimationAssumptions: '30 man-days; third-party API subscription at AED 80K/year',
    comments: 'Scoring criteria must be approved by procurement and legal before automation',
  },
  {
    id: 'opp-015',
    name: 'Predictive Maintenance Analytics',
    code: 'EXP.1.5.2',
    domain: 'Audit & Assurance',
    gcOwner: 'ADNOC HQ',
    applicability: { proposedTo: 4, acceptedBy: 2 },
    status: 'Draft',
    workflowStatus: 'Proposed',
    description:
      'Implement predictive maintenance analytics platform leveraging IoT sensor data and machine learning to reduce unplanned downtime.',
    functionalCapabilities:
      'Sensor data ingestion, failure prediction models, maintenance scheduling optimization',
    keyPrerequisites: 'IoT sensors on critical assets, historical maintenance data, ML platform',
    keyBusinessBenefits: 'Reduces unplanned downtime by 35%, extends asset lifecycle by 20%',
    solutionType: 'IoT & Analytics',
    illustrativePlatform: 'IoT (Azure IoT Hub), AI/ML (Azure ML)',
    aiApplicability: 'Yes',
    impactedBusinessProcesses: 'Asset Management, Operations, Maintenance Planning',
    estimatedImplementationDuration: 9,
    estimatedImplementationCost: 7000000,
    proposedPriority: 'High',
    effortManDays: 'High',
    investmentCost: 'High',
    riskLevel: 'Medium',
    technicalDifficulty: 'High',
    resourceRequirements: 'High',
    costSavingRevenuePotential: 'High',
    customerSatisfactionIncrease: 'High',
    businessRiskReduction: 'High',
    efficiencyImprovement: 'Medium',
    impactType: 'Revenue Generation',
    impactReason: 'Cost Optimization',
    drivers: 'Asset reliability, operational excellence, ADNOC 2030 strategy',
    costValueEstimationAssumptions:
      'IoT deployment AED 1.8M; Azure IoT Hub AED 400K/year; 180 man-days implementation',
    comments: 'Pilot recommended on 3 critical assets before full fleet rollout',
  },
]
