import type { DomainItem } from '../types/process'

export const ASSESSMENT_DATA:DomainItem[] = [ // keep type any until we finalize the data structure
  {
    id: 'd1',
    domain: 'dom-005',
    level1Items: [
      {
        id: 'l1-1',
        level1Name: 'Exploration',
        level1Code: 'EXP.1',
        level2Items: [
          {
            id: 'l2-1',
            level2Name: 'Regional Studies',
            level2Code: 'EXP.1.1',
            level3Items: [
              {
                id: 'l3-1',
                level3Name: 'Basin Modeling',
                level3Code: 'EXP.1.1.3',
                groupCompany: 'ADNOC SA',
                status:'Pending approval',
                site: 'A',
                description: 'Define the structural and stratigraphic framework of the basin, including major faults, horizons, and depositional environments.',
                centrallyGovernedProcess: 'Yes',
                sharedService: {services:12,shared:3},
                businessUnit: ['Exploration'],
                ResponsibleDigitalTeam : ['Data Analytics'],
                processCriticality: 'Standard',
                UsersImpacted:'Small (1-50)',
                scaleOfProcess:'Medium: (bigger team within one department)',
                automationMaturityLevel:'Fully Automated',
                automationLevel:'10%',
                currentApplicationsSystems:[{id:'excel' , name:'Microsoft 365 - Excel'}],
                OngoingAutomationDigitalInitiatives:'N/A',
                businessRecommendationForAutomation:'Should be kept as is',
                keyChallengesAutomationNeeds:'none',
                AIPowered:'No',
                AIPoweredUseCase:'N/A',
                autonomousUseCaseEnabled:'No',
                AutonomousUseCaseDescriptionComment:'N/A',
                ProcessCycle:'Annually',
                processRepetitionWithinCycle:'1',
                totalPersonnelExecutingFTE:'5',
                totalProcessDurationDays:'30',
                timeSpentOnManualTasksPercent:'80%',
                keyManualSteps:'1.Data collection, model setup, result interpretation',
                northStarTargetAutomation:'Keep as is',
                targetAutomationLevelPercent:'60%',
                SMEFeedback:'Significant time spent on manual data collection and model setup. Automation could free up time for more value-added analysis.',
                toBeAIPowered:'Yes',
                toBeAIPoweredComments:'AI could be used to assist with result interpretation and identify patterns in the data.',
                rateCardAED:'500 AED',
                costOfManualEffortAED:'120000 AED',
                markedAsReviewed:'false',
                reviewedOn:'',
                businessFocalPoint:['John Doe'],
                digitalFocalPoint:['Jane Smith'],
                publishedDate:'2024-01-15',
                submittedBy:'John Doe',
                submittedOn:'2024-01-10',
                level4Items: [
                  {
                    id: 'l4-1-1',
                    level4Name: 'Define basin framework',
                    level4Code: 'EXP.1.1.3.1',
                    status:'Published',
                    site: 'C',
                    description: 'Define the structural and stratigraphic framework of the basin, including major faults, horizons, and depositional environments.',
                    centrallyGovernedProcess: 'no',
                    sharedService: {services:12,shared:3},
                    businessUnit: ['Internal Audit Department (Operations)','Exploration'],
                    processCriticality: 'High',
                     
                  },
                 
                  {
                    id: 'l4-1-3',
                    level4Name: 'Source rock maturity assessment',
                    level4Code: 'EXP.1.1.3.3', 
                    status:'Published',
                    site: 'B',
                    description: 'Define the structural and stratigraphic framework of the basin, including major faults, horizons, and depositional environments.',
                    centrallyGovernedProcess: 'Yes',
                    sharedService: {services:12,shared:3},
                    businessUnit: ['Exploration','testing'],
                    processCriticality: 'High',
                  },
                  {
                    id: 'l4-1-4',
                    level4Name: 'Charge and migration modeling',
                    level4Code: 'EXP.1.1.3.4',
                    status:'Pending approval',
                    site: 'B',
                    description: 'Define the structural and stratigraphic framework of the basin, including major faults, horizons, and depositional environments.',
                    centrallyGovernedProcess: 'no',
                    sharedService: {services:12,shared:3},
                    businessUnit: ['Exploration'],
                    markedAsReviewed:'true',
                    reviewedOn:'2024-02-01',
                    processCriticality: 'High',
                    currentApplicationsSystems:[{id:'excel' , name:'Microsoft 365 - Excel'}]
                   
                  },
                ],
              },
              {
                id: 'l3-2',
                level3Name: 'Geophysical Data Interpretation',
                level3Code: 'EXP.1.1.4',
                groupCompany: 'ADNOC SA',
                status:'Pending approval',
                site: 'A',
                description: 'Define the structural and stratigraphic framework of the basin, including major faults, horizons, and depositional environments.',
                centrallyGovernedProcess: 'Yes',
                sharedService: {services:12,shared:3},
                businessUnit: ['Exploration'],
                ResponsibleDigitalTeam : ['Data Analytics'],
                processCriticality: 'High',
                UsersImpacted:'Small (1-50)',
                level4Items: [],
              },
            ],
          },
          {
            id: 'l2-2',
            level2Name: 'Play Assessment (PA)',
            level2Code: 'EXP.1.2',
            level3Items: [
              {
                id: 'l3-3',
                level3Name: 'Dashboard Exploration Test',
                level3Code: 'EXP.1.3.3',
                groupCompany: 'ADNOC SA',
                status:'Pending approval',
                site: 'A',
                description: 'Define the structural and stratigraphic framework of the basin, including major faults, horizons, and depositional environments.',
                centrallyGovernedProcess: 'Yes',
                sharedService: {services:12,shared:3},
                businessUnit: ['Exploration'],
                ResponsibleDigitalTeam : ['Data Analytics'],
                processCriticality: 'Standard',
                UsersImpacted:'Small (1-50)',
                scaleOfProcess:'Medium: (bigger team within one department)',
                automationMaturityLevel:'Fully Automated',
                automationLevel:'50%',
                currentApplicationsSystems:[{id:'excel' , name:'Microsoft 365 - Excel'}],
                OngoingAutomationDigitalInitiatives:'N/A',
                businessRecommendationForAutomation:'Should be kept as is',
                keyChallengesAutomationNeeds:'none',
                AIPowered:'Yes',
                AIPoweredUseCase:'N/A',
                autonomousUseCaseEnabled:'No',
                AutonomousUseCaseDescriptionComment:'N/A',
                ProcessCycle:'Annually',
                processRepetitionWithinCycle:'1',
                totalPersonnelExecutingFTE:'5',
                totalProcessDurationDays:'30',
                timeSpentOnManualTasksPercent:'80%',
                keyManualSteps:'1.Data collection, model setup, result interpretation',
                northStarTargetAutomation:'Keep as is',
                targetAutomationLevelPercent:'60%',
                SMEFeedback:'Significant time spent on manual data collection and model setup. Automation could free up time for more value-added analysis.',
                toBeAIPowered:'Yes',
                toBeAIPoweredComments:'AI could be used to assist with result interpretation and identify patterns in the data.',
                rateCardAED:'400 AED',
                costOfManualEffortAED:'120000 AED',
                markedAsReviewed:'true',
                reviewedOn:'2024-02-01',
                businessFocalPoint:['John Doe'],
                digitalFocalPoint:['Jane Smith'],
                publishedDate:'2024-01-15',
                submittedBy:'John Doe',
                submittedOn:'2024-01-10',
                level4Items:[]
              },
              {
                id: 'l3-4',
                level3Name: 'Project & Workflow Strategy (PA-01)',
                level3Code: 'EXP.1.2.2',
                groupCompany: 'ADNOC SA',
                status:'Pending approval',
                site: 'A',
                description: 'Define the structural and stratigraphic framework of the basin, including major faults, horizons, and depositional environments.',
                centrallyGovernedProcess: 'Yes',
                sharedService: {services:12,shared:3},
                businessUnit: ['Exploration'],
                ResponsibleDigitalTeam : ['Data Analytics'],
                processCriticality: 'High',
                currentApplicationsSystems:[{id:'excel' , name:'Microsoft 365 - Excel'}],
                markedAsReviewed:'false',
                reviewedOn:'',
                level4Items: [
                  {
                    id: 'l4-4-1',
                    level4Name: 'Define exploration KPIs',
                    level4Code: 'EXP.1.2.2.1',
                  },
                ],
              },
              {
                id: 'l3-5',
                level3Name: 'Regional Data Gathering & QC (PA-02)',
                level3Code: 'EXP.1.2.3',
                groupCompany: 'ADNOC HQ',
                status:'Pending approval',
                site: 'A',
                description: 'Define the structural and stratigraphic framework of the basin, including major faults, horizons, and depositional environments.',
                centrallyGovernedProcess: 'Yes',
                sharedService: {services:12,shared:3},
                businessUnit: ['Exploration'],
                ResponsibleDigitalTeam : ['Data Analytics'],
                processCriticality: 'High',
                currentApplicationsSystems:[{id:'excel' , name:'Microsoft 365 - Excel'}],

                level4Items: [
                  {
                    id: 'l4-5-1',
                    level4Name: 'Seismic data conditioning',
                    level4Code: 'EXP.1.2.3.1',
                  },
                  {
                    id: 'l4-5-2',
                    level4Name: 'Regional seismic interpretation',
                    level4Code: 'EXP.1.2.3.2',
                  },
                ],
              },
              {
                id: 'l3-6',
                level3Name: 'Regional Subsurface Interpretation',
                level3Code: 'EXP.1.2.4',
                groupCompany: 'ADNOC SA',
                status:'Pending approval',
                site: 'A',
                description: 'Define the structural and stratigraphic framework of the basin, including major faults, horizons, and depositional environments.',
                centrallyGovernedProcess: 'Yes',
                sharedService: {services:12,shared:3},
                businessUnit: ['Exploration'],
                ResponsibleDigitalTeam : ['Data Analytics'],
                processCriticality: 'High',
                level4Items: [
                  {
                    id: 'l4-9-1',
                    level4Name: 'Define basin framework',
                    level4Code: 'EXP.1.5.3.1',
                    status:'Published',
                    site: 'A',
                    description: 'Define the structural and stratigraphic framework of the basin, including major faults, horizons, and depositional environments.',
                    centrallyGovernedProcess: 'Yes',
                    sharedService: {services:12,shared:3},
                    businessUnit: ['Exploration'],
                    processCriticality: 'High',
                     
                  }],
              },
            ],
          },
        ],
      },
      {
        id: 'l1-2',
        level1Name: 'Field Development Planning',
        level1Code: 'EXP.2',
        level2Items: [
          {
            id: 'l2-3',
            level2Name: 'Subsurface Modeling',
            level2Code: 'EXP.2.1',
            level3Items: [
              {
                id: 'l3-7',
                level3Name: 'Static Model Construction',
                level3Code: 'EXP.2.1.1',
                groupCompany: 'ADNOC SA',
                status:'Pending approval',
                site: 'A',
                description: 'Define the structural and stratigraphic framework of the basin, including major faults, horizons, and depositional environments.',
                centrallyGovernedProcess: 'Yes',
                sharedService: {services:12,shared:3},
                businessUnit: ['Exploration'],
                ResponsibleDigitalTeam : ['Data Analytics'],
                OngoingAutomationDigitalInitiatives:'N/A',
                processCriticality: 'High',
                level4Items: [
                  {
                    id: 'l4-7-1',
                    level4Name: 'Structural framework build',
                    level4Code: 'EXP.2.1.1.1',
                  },
                  {
                    id: 'l4-7-2',
                    level4Name: 'Facies and property modelling',
                    level4Code: 'EXP.2.1.1.2',
                  },
                ],
              },
            
            ],
          },
        ],
      },
    ],
  },

]
