export const PROESS_DETAILS = [{
  name: 'Define basin framework',
  groupCompany: '12345',
  domain: 'Process 1',
  code: 'SGSAUD.1.1.3.1',
  status: 'Draft',
  stageCurrent: '1',
  stageTotal: '3',
  processApplicapility: true,
  lastPublishedDate: '2024-01-01',
  markedReviewDate: '2024-12-31',
  level1Name: 'Exploration',
  level2Name: 'Regional studies',
  level3Name: 'Basin Modeling',
  level4Name: 'Define basin framework',
  centrallyGovernedProcess: 'yes',
  sharedServiceProcess: 'no',
  customName: 'Default Name',
  customDescription: 'Default Description',
  processDescription: 'Default Process Description',
  responsibleBusinessFocalPoint: [
    {
      id: 'user1',
      name: 'Fatima Al Nuaimi',
      img: 'https://t4.ftcdn.net/jpg/06/45/77/79/360_F_645777959_fNnaNoeVO4qxCNPW9MWr3gQlPFSGA9yL.jpg',
    },
  ],
  responsibleDigitalFocalPoint: [
    {
      id: 'user12',
      name: 'Ahmed Al Mansoori',
      img: 'https://t4.ftcdn.net/jpg/06/45/77/79/360_F_645777959_fNnaNoeVO4qxCNPW9MWr3gQlPFSGA9yL.jpg',
    },
  ],
  numberOfPeopleInvolved: 'High (500-1000)',
  scaleOfProcess: 'Medium: (bigger team within one department)',
  automationMaturityLevel: 'Fully Automated',
  automationLevel: '10%',
  currentApplicationsSystems: ['Microsot Excel', 'Petrel'],
  OngoingAutomationDigitalInitiatives: 'N/A',
  businessRecommendationForAutomation: 'Should be kept as is',
  keyChallengesAutomationNeeds: 'none',
  AIPowered: 'No',
  AIPoweredUseCase: '',
  autonomousUseCaseEnabled: 'No',
  AutonomousUseCaseDescriptionComment: 'N/A',
  processCriticality: 'Standard',
  keyManualSteps: '1.Data collection, model setup, result interpretation',
}]
